export interface PanicControl {
  payments?: boolean
  librarySellVideos?: boolean
  sendDocuments?: boolean
  uploadGallery?: boolean
  pingdomVisitorInsightsRun?: boolean
  ocrImages?: boolean
  lastSeen?: boolean
  geolocation?: boolean
  nfseService?: boolean
  adCounterPerFilter?: boolean
  whatsappBotValidateService?: boolean
  textValidatorFatalChat?: boolean
  hotjarCapture?: boolean
  chatGeolocation?: boolean
  pwaBannerShow?: boolean
  fatalStories?: boolean
  userDocs?: boolean
  adPanelStatistics?: boolean
  fatalStoriesMetaData?: boolean
  textValidatorConsumer?: boolean
  fatalStoriesFeedbackForm?: boolean
  elasticSearch?: boolean
  followFeature?: boolean
  ageAgreementTerms?: boolean
  requireDocumentsFromClones?: boolean
  elasticSearchSurvey?: boolean
  chargebackPayment?: boolean
  libraryVideosWarning?: boolean
  libraryVideosHistory?: boolean
  fixInconsistencyAgeBirthDate?: boolean
  requireDocumentsFromOldAds?: boolean
  sendNotificationsOfRemainingTimeForOldAdsSendDocs?: boolean
  marketingCitiesTexts?: boolean
  clearImageCacheCf?: boolean
  coupons?: boolean
  subscriptions?: boolean
  cleaningCloudflare?: boolean
  sitelinkHome?: boolean
  facialAuthentication?: boolean
  alertCookieDecryptSlack?: boolean
  denounces2?: boolean
  comparisonMediaV4?: boolean
  comparisonMediaV4DowngradeToV3?: boolean
  cacheConnectionClose?: boolean
  homev2Redirect?: boolean
  usersWallet?: boolean
  newHeaderAndMenu?: boolean
  metricCaptureByKenesis?: boolean
  metricQueryByElasticsearch?: boolean
  hideFromListingAdsWithoutPlans?: boolean
  subscriptionsFront?: boolean
  apmMysqlQuery?: boolean
  statusSeen?: boolean
  termsUseUpdate?: boolean
  restrictedNames?: boolean
  hideFromOneHourSuperTopPlan?: boolean
  movidesk?: boolean
  showDealtalkButton?: boolean
  voucherChangeCity?: boolean
  voucherChangeName?: boolean
  showNewAdProfile?: boolean
  pixPlans?: boolean
  adPanelV2?: boolean
  plan6Flash?: boolean
  virtualAdList?: boolean
  comparisonMediaV4TutorialVideoYoutube?: boolean
  jobsOrderLikeUpdate?: boolean
  seoServiceListing?: boolean
  seoMainAdsMainCities?: boolean
  seoApmMysqlQuery?: boolean
  comparisonMediaV4HidePages?: boolean
  plan7ListPoints?: boolean
  gifts?: boolean
  adNudityModeration?: boolean
  consumerBottomNavbar?: boolean
  simulateRankNewCity?: boolean
  newTemporaryDeactivationAdProfile?: boolean
  newRemovalAdProfile?: boolean
  phoneAccountTheftSecurity?: boolean
  virtualListingChange?: boolean
  adSuspensionService?: boolean
  pixVouchers?: boolean
  consumerPanelRoute?: boolean
  showCompanionDayVideo?: boolean
  penaltyFee?: boolean
  onboardNewAdRegister?: boolean
  fbotApi?: boolean
  penaltyFeeCard?: boolean
  penaltyFeeBillet?: boolean
  penaltyFeePix?: boolean
  consumerPanel?: boolean
  consumerApi?: boolean
  fpayCreditCardPayment?: boolean
  facialAuthenticationV2?: boolean
  consumerPremiumMedias?: boolean
  adSuspensionServicePix?: boolean
  adSuspensionServiceCard?: boolean
  adSuspensionServiceBillet?: boolean
  consumerPremiumPayment?: boolean
  seoAdListingIndexing?: boolean
  generalCreditCardPayment?: boolean
  generalBilletPayment?: boolean
  generalPixPayment?: boolean
  safe2payPayment?: boolean
  userScore?: boolean
  fpayChargebackDebitPixPayment?: boolean
  safe2paySubscriptions?: boolean
  reviewPremium?: boolean
  adminCourtesies?: boolean
  consumerLastSeen?: boolean
  voucherCreditCardChangeCity?: boolean
  voucherCreditCardChangeName?: boolean
  consumerLists?: boolean
  pixPlanPurchaseDiscount?: boolean
  withdraws?: boolean
  adProfileMetrics?: boolean
  plan6FlashStopwatch?: boolean
  showTagNewAd?: boolean
  showTagNewInCity?: boolean
  showTagReturnInTheCity?: boolean
  showTagNewMedia?: boolean
  consumerListsWrite?: boolean
  fcheckout?: boolean
  newRegistrationFlow?: boolean
  consumerMetric?: boolean
  marketingBanner?: boolean
  adPremiumListing?: boolean
  rdStationService?: boolean
  facialAuthenticationV2LivenessCheck?: boolean
  consumerNewsletterService?: boolean
  adSeeReviewsAboutHimself?: boolean
  consumerListsPersonalized?: boolean
  seoPagesCdnCacheControlMiddleware?: boolean
  consumerManagePlans?: boolean
  fcheckoutChargebackBlock?: boolean
  fcheckoutChargebackDebitsList?: boolean
  fcheckoutConsumerPlans?: boolean
  adCardFakeList?: boolean
  fatalBlog?: boolean
  facialAuthenticationV2DeviceVerification?: boolean
  seoPagesCdnImageResize?: boolean
  consumerHistory?: boolean
  consumerHistoryWrite?: boolean
  publicities?: boolean
  registrationAd?: boolean
  autoClosePostPremium?: boolean
  userScoreDatabaseLog?: boolean
  fcheckoutRecurrence?: boolean
  seoNearbyCitiesListing?: boolean
  documentReactivationAd?: boolean
  fatalInvite?: boolean
  fatalInviteAd?: boolean
  fatalInviteConsumer?: boolean
  consumerPlanExpiresModal?: boolean
  consumerPlanPanelNotification?: boolean
  consumerPlanHistoric?: boolean
  fatalInviteConsumerReward?: boolean
  fatalInviteAdReward?: boolean
  fpaySyncPayments?: boolean
  consumerListsFilters?: boolean
  fcheckoutOnlyWinterfell?: boolean
  consumerHistoryFilters?: boolean
  consumerPlanMonthlyPurchasePix?: boolean
  knowMoreAboutConsumerPlans?: boolean
  removePenaltyFeeValue?: boolean
  feed?: boolean
  consumerPlanPremiumTrial?: boolean
  reviewsConsumerBasic?: boolean
  reviewsConsumerFree?: boolean
  seoShowListingMdcExpired?: boolean
  comparisonMediaHistory?: boolean
  notificationPublicSection?: boolean
  feedIndexRoutes?: boolean
}
